services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: template-rabbitmq
      environment:
        - 'RABBITMQ_DEFAULT_PASS=secret'
        - 'RABBITMQ_DEFAULT_USER=myuser'
      ports:
          - 5673:5672
          - 15673:15672
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq
      restart: always
  redis:
      image: redis:alpine
      container_name: template-redis
      command: redis-server --save 20 1 --loglevel warning
      ports:
          - 6380:6379
      volumes:
          - redis_data:/data
      restart: always
  postgres:
      image: timescale/timescaledb-ha:pg17.4-ts2.19.3
      container_name: tamplate-postgres
      volumes:
          - ./postgis-data:/var/lib/postgresql
      environment:
        - 'POSTGRES_DB=mydatabase'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=myuser'
      ports:
          - 6433:5432
      restart: always
      healthcheck:
          test: "pg_isready -h 127.0.0.1 -U clever"
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 1m
  keycloak:
      image: quay.io/keycloak/keycloak:24.0
      environment:
          KC_HOSTNAME: localhost
          KC_HOSTNAME_PORT: 7080
          KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: "true"
          KC_LOG_LEVEL: info
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
          interval: 15s
          timeout: 2s
          retries: 15
      command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
      ports:
          - "7080:7080"
          - "7443:7443"
      networks:
          - local_network
      volumes:
        - ./keycloak-data:/opt/keycloak/data/h2/
volumes:
    rabbitmq_data:
    redis_data:
    geoserver-data:
    geo-db-data:
    geoserver-gwc:
    postgres-data:
        external: false
networks:
    local_network:
        driver: bridge
