services:
  rabbitmq:
      image: rabbitmq:3-management
      container_name: template-rabbitmq
      environment:
        - 'RABBITMQ_DEFAULT_PASS=secret'
        - 'RABBITMQ_DEFAULT_USER=myuser'
      ports:
          - 5673:5672
          - 15673:15672
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq
      restart: always
  redis:
      image: redis:alpine
      container_name: template-redis
      command: redis-server --save 20 1 --loglevel warning
      ports:
          - 6380:6379
      volumes:
          - redis_data:/data
      restart: always
  postgres:
      image: timescale/timescaledb-ha:pg17.4-ts2.19.3
      container_name: tamplate-postgres
      volumes:
          - ./postgis-data:/var/lib/postgresql
      environment:
        - 'POSTGRES_DB=mydatabase'
        - 'POSTGRES_PASSWORD=secret'
        - 'POSTGRES_USER=myuser'
      ports:
          - 6433:5432
      restart: always
      healthcheck:
          test: "pg_isready -h 127.0.0.1 -U clever"
          interval: 1m30s
          timeout: 10s
          retries: 3
          start_period: 1m
volumes:
    rabbitmq_data:
    redis_data:
    geoserver-data:
    geo-db-data:
    geoserver-gwc:
    postgres-data:
        external: false
