spring.application.name=microservice.template.core

server.port=8080

# ###############################
# Datasource
# ###############################
spring.datasource.type=org.postgresql.ds.PGSimpleDataSource
spring.datasource.url=jdbc:postgresql://127.0.0.1:6433/mydatabase?prepareThreshold=0
spring.datasource.username=myuser
spring.datasource.password=secret
